name: ci

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 2
    - name: build
      run: swift build
